# Generated by Django 4.1.3 on 2022-11-23 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=200)),
                ('seat_cap', models.IntegerField(default=0)),
                ('dept_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('studen_name', models.CharField(max_length=200)),
                ('student_phone_number', models.CharField(max_length=15)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.department')),
            ],
        ),
    ]
