# Generated by Django 4.1.3 on 2022-11-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studen_name',
            new_name='student_name',
        ),
    ]
