# Generated by Django 3.2.10 on 2022-05-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ages', models.IntegerField()),
                ('dateEinroled', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
